# Frontend configuration
[frontend_config]
cors = [
    "http://localhost:5666",
    "http://127.0.0.1:5666",
    "http://localhost:5668",
    "http://127.0.0.1:5668",
]

# Backend configuration
[backend_config]
address = "127.0.0.1:7878"
# JWT configuration
[backend_config.jwt]
access_secret = "your_jwt_secret"
refresh_secret = "your_jwt_refresh_secret"
# access_expiration = 3600
# refresh_expiration = 604800

# Logging configuration
[log_config]
enable_debug = false
prefix = "paper-backend"

# MongoDB configuration
[mongo_config]
uri = "mongodb://localhost:27017"
db_name = "paper"
